import { createSwaggerSpec } from 'next-swagger-doc';
import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET() {
  const spec = createSwaggerSpec({
    apiFolder: 'src/app/api',
    schemaFolders: ['src/lib'],
    definition: {
      openapi: '3.0.0',
      info: { title: 'Luxury Estate API', version: '1.0.0', description: 'REST API for luxury real estate platform' },
      servers: [{ url: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000', description: 'Local Dev' }],
      components: {
        securitySchemes: {
          BearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
            description: 'JWT token obtained from /api/auth (or use X-User-ID header in dev mode)',
          },
        },
        schemas: {
          // --- Input Schemas ---
          PersonInput: {
            type: 'object', required: ['firstName', 'lastName', 'personTypeId', 'slug'],
            properties: {
              firstName: { type: 'string', example: 'John' },
              lastName: { type: 'string', example: 'Doe' },
              email: { type: 'string', format: 'email', example: 'john@example.com' },
              phone: { type: 'string', example: '+1-555-1234' },
              personTypeId: { type: 'integer', example: 1 },
              slug: { type: 'string', example: 'john-doe' },
              isAssociate: { type: 'boolean', default: false },
            },
          },
          AssociateInput: {
            type: 'object', required: ['personId', 'associateTypeId', 'slug'],
            properties: {
              personId: { type: 'integer', example: 1 },
              associateTypeId: { type: 'integer', example: 1 },
              slug: { type: 'string', example: 'john-doe-agent' },
              agencyId: { type: 'integer', nullable: true },
              officeId: { type: 'integer', nullable: true },
              personRoleId: { type: 'integer', nullable: true },
              supervisorId: { type: 'integer', nullable: true },
              department: { type: 'string', example: 'Luxury Sales' },
              title: { type: 'string', example: 'Senior Agent' },
              licenseNumber: { type: 'string', example: 'CAL-123456' },
              photoId: { type: 'integer', nullable: true },
              videoId: { type: 'integer', nullable: true },
              contactMethodId: { type: 'integer', nullable: true },
            },
          },
          AgencyInput: {
            type: 'object', required: ['name'],
            properties: {
              name: { type: 'string', example: 'Luxury Estates Inc.' },
              addressId: { type: 'integer', nullable: true },
              logoId: { type: 'integer', nullable: true },
              bannerId: { type: 'integer', nullable: true },
              email: { type: 'string', format: 'email' },
              phone: { type: 'string' },
            },
          },
          BlogPostInput: {
            type: 'object', required: ['title', 'slug', 'content', 'authorPersonId'],
            properties: {
              title: { type: 'string', example: 'Market Trends 2026' },
              slug: { type: 'string', example: 'market-trends-2026' },
              excerpt: { type: 'string' },
              content: { type: 'string' },
              published: { type: 'boolean', default: false },
              featuredImageId: { type: 'integer', nullable: true },
              authorPersonId: { type: 'integer', example: 1 },
            },
          },
          LoginInput: {
            type: 'object', required: ['email', 'password'],
            properties: {
              email: { type: 'string', format: 'email', example: 'john@example.com' },
              password: { type: 'string', format: 'password', example: 'mypassword' },
            },
          },
          AuthRegisterInput: {
            type: 'object', required: ['personId', 'email', 'password'],
            properties: {
              personId: { type: 'integer', example: 1 },
              email: { type: 'string', format: 'email', example: 'john@example.com' },
              password: { type: 'string', format: 'password', example: 'mypassword' },
            },
          },
          AuthAccountInput: {
            type: 'object', required: ['personId', 'email', 'passwordHash'],
            properties: {
              personId: { type: 'integer', example: 1 },
              email: { type: 'string', format: 'email' },
              passwordHash: { type: 'string' },
              provider: { type: 'string', default: 'credentials' },
            },
          },
          OfficeInput: {
            type: 'object', required: ['name', 'slug'],
            properties: {
              phone: { type: 'string', example: '555-0001' },
              name: { type: 'string', example: 'Buckhead Office' },
              slug: { type: 'string', example: 'buckhead-office' },
              addressId: { type: 'integer', nullable: true },
            },
          },
          AddressInput: {
            type: 'object',
            required: ['addressStreet', 'addressCityId', 'addressRegionId', 'postalCode', 'addressCountryId'],
            properties: {
              recipient: { type: 'string' },
              organization: { type: 'string' },
              addressStreet: { type: 'string' },
              addressCityId: { type: 'integer' },
              addressRegionId: { type: 'integer' },
              postalCode: { type: 'string' },
              addressCountryId: { type: 'integer' },
              latitude: { type: 'number' },
              longitude: { type: 'number' },
            },
          },
          ImageInput: {
            type: 'object', required: ['uri'],
            properties: {
              uri: { type: 'string', format: 'uri', example: 'https://example.com/image.jpg' },
              isPersonal: { type: 'boolean', default: false },
            },
          },
          VideoInput: {
            type: 'object', required: ['uri'],
            properties: {
              uri: { type: 'string', format: 'uri', example: 'https://example.com/video.mp4' },
              isPersonal: { type: 'boolean', default: false },
            },
          },
          PropertyInput: {
            type: 'object', required: ['name', 'description', 'propertyTypeId', 'propertyStatusId', 'slug'],
            properties: {
              name: { type: 'string', example: 'Ocean View Villa' },
              slug: { type: 'string', example: 'ocean-view-villa' },
              description: { type: 'string' },
              summary: { type: 'string' },
              price: { type: 'number', example: 2500000 },
              bedrooms: { type: 'integer', example: 4 },
              bathrooms: { type: 'integer', example: 3 },
              areaSqft: { type: 'number' },
              propertyTypeId: { type: 'integer' },
              propertyStatusId: { type: 'integer' },
              streetAddress: { type: 'string' },
              addressLocality: { type: 'string' },
              addressRegion: { type: 'string' },
              postalCode: { type: 'string' },
              addressCountry: { type: 'string' },
              garageSpaces: { type: 'integer' },
              builtYear: { type: 'integer' },
              lotSize: { type: 'number' },
              hoaFees: { type: 'number' },
              mlsId: { type: 'string' },
              latitude: { type: 'number' },
              longitude: { type: 'number' },
              isFeatured: { type: 'boolean' },
              isPublished: { type: 'boolean' },
              virtualTourUrl: { type: 'string' },
              videoTourUrl: { type: 'string' },
              agencyId: { type: 'integer', nullable: true },
              agentId: { type: 'integer', nullable: true },
              addressId: { type: 'integer', nullable: true },
            },
          },
          ContactRequestInput: {
            type: 'object', required: ['firstName', 'lastName', 'email', 'requestTypeId', 'message'],
            properties: {
              firstName: { type: 'string', example: 'John' },
              lastName: { type: 'string', example: 'Doe' },
              email: { type: 'string', format: 'email', example: 'john@example.com' },
              phone: { type: 'string', example: '+1-555-1234' },
              companyName: { type: 'string', example: 'Acme Corp' },
              jobTitle: { type: 'string', example: 'CEO' },
              requestTypeId: { type: 'integer', example: 1 },
              subject: { type: 'string', example: 'Partnership inquiry' },
              message: { type: 'string', example: 'I am interested in...' },
              contactMethodId: { type: 'integer', nullable: true, example: 1 },
              leadSourceId: { type: 'integer', nullable: true, example: 1 },
              requestStatusId: { type: 'integer', example: 1 },
              marketingConsent: { type: 'boolean', default: false },
            },
          },
          LeadSourceInput: {
            type: 'object', required: ['code', 'name'],
            properties: {
              code: { type: 'string', example: 'WEBSITE' },
              name: { type: 'string', example: 'Website' },
              description: { type: 'string', example: 'Direct website visit' },
            },
          },
          ContactMethodInput: {
            type: 'object', required: ['code', 'name'],
            properties: {
              code: { type: 'string', example: 'EMAIL' },
              name: { type: 'string', example: 'Email' },
            },
          },
          PropertyImageInput: {
            type: 'object', required: ['propertyId', 'imageId'],
            properties: {
              propertyId: { type: 'integer' },
              imageId: { type: 'integer' },
              isBanner: { type: 'boolean', default: false },
            },
          },
          PropertyVideoInput: {
            type: 'object', required: ['propertyId', 'videoId'],
            properties: {
              propertyId: { type: 'integer' },
              videoId: { type: 'integer' },
            },
          },
          PropertyReviewInput: {
            type: 'object', required: ['propertyId', 'personId', 'rating'],
            properties: {
              propertyId: { type: 'integer', example: 1 },
              personId: { type: 'integer', example: 1 },
              associateId: { type: 'integer', nullable: true, example: 1 },
              moderationStatusId: { type: 'integer', nullable: true, example: 1 },
              rating: { type: 'integer', minimum: 1, maximum: 5, example: 5 },
              title: { type: 'string', example: 'Amazing property!' },
              comment: { type: 'string' },
              isPublished: { type: 'boolean', default: false },
            },
          },
          ReviewModerationStatuses: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              name: { type: 'string' },
              code: { type: 'string' },
              description: { type: 'string', nullable: true },
            },
          },

          TourRequestInput: {
            type: 'object', required: ['propertyId', 'clientFirstName', 'clientLastName', 'clientEmail', 'primaryAssociateId', 'scheduledDate'],
            properties: {
              propertyId: { type: 'integer', example: 1 },
              clientPersonId: { type: 'integer', nullable: true, example: 1 },
              clientFirstName: { type: 'string', example: 'John' },
              clientLastName: { type: 'string', example: 'Doe' },
              clientEmail: { type: 'string', format: 'email', example: 'john@example.com' },
              clientPhone: { type: 'string', example: '+1-555-1234' },
              primaryAssociateId: { type: 'integer', example: 1 },
              secondaryAssociateId: { type: 'integer', nullable: true, example: 2 },
              tourTypeId: { type: 'integer', example: 1 },
              tourStatusId: { type: 'integer', example: 1 },
              scheduledDate: { type: 'string', format: 'date-time', example: '2026-06-15T14:00:00Z' },
              clientMessage: { type: 'string' },
              associateNotes: { type: 'string' },
              contactMethodId: { type: 'integer', nullable: true, example: 1 },
              leadSourceId: { type: 'integer', nullable: true, example: 1 },
            },
          },

          // --- Response Schemas ---
          SuccessResponse: {
            type: 'object',
            properties: {
              success: { type: 'boolean', example: true },
              data: { type: 'object' },
            },
          },
          ErrorResponse: {
            type: 'object',
            properties: {
              error: { type: 'string', example: 'Not found' },
              detail: { type: 'string' },
            },
          },
          PersonResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              firstName: { type: 'string' },
              lastName: { type: 'string' },
              fullName: { type: 'string' },
              email: { type: 'string' },
              phone: { type: 'string' },
              personTypeId: { type: 'integer' },
              slug: { type: 'string' },
              isAssociate: { type: 'boolean' },
            },
          },
          AssociateResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              personId: { type: 'integer' },
              associateTypeId: { type: 'integer' },
              agencyId: { type: 'integer', nullable: true },
              officeId: { type: 'integer', nullable: true },
              slug: { type: 'string' },
              department: { type: 'string' },
              title: { type: 'string' },
              licenseNumber: { type: 'string' },
              person: { $ref: '#/components/schemas/PersonResponse' },
            },
          },
          AddressResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              recipient: { type: 'string', nullable: true },
              organization: { type: 'string', nullable: true },
              addressStreet: { type: 'string' },
              addressCityId: { type: 'integer' },
              addressRegionId: { type: 'integer' },
              postalCode: { type: 'string' },
              addressCountryId: { type: 'integer' },
              cityName: { type: 'string' },
              regionCode: { type: 'string' },
              countryCode: { type: 'string' },
              latitude: { type: 'number', nullable: true },
              longitude: { type: 'number', nullable: true },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          ImageResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              uri: { type: 'string', format: 'uri' },
              isPersonal: { type: 'boolean' },
            },
          },
          VideoResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              uri: { type: 'string', format: 'uri' },
              isPersonal: { type: 'boolean' },
            },
          },
          OfficeResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              phone: { type: 'string', nullable: true },
              name: { type: 'string' },
              slug: { type: 'string' },
              tenantId: { type: 'integer' },
              addressId: { type: 'integer', nullable: true },
              address: { $ref: '#/components/schemas/AddressResponse' },
            },
          },
          AgencyResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              name: { type: 'string' },
              slug: { type: 'string' },
              description: { type: 'string', nullable: true },
              phone: { type: 'string', nullable: true },
              email: { type: 'string', nullable: true },
              isFeatured: { type: 'boolean' },
              isVerified: { type: 'boolean' },
              address: { $ref: '#/components/schemas/AddressResponse' },
            },
          },
          BlogPostResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              title: { type: 'string' },
              slug: { type: 'string' },
              excerpt: { type: 'string', nullable: true },
              content: { type: 'string' },
              published: { type: 'boolean' },
              authorPersonId: { type: 'integer' },
              authorPerson: { $ref: '#/components/schemas/PersonResponse' },
              createdAt: { type: 'string', format: 'date-time' },
            },
          },
          PropertyResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              name: { type: 'string' },
              description: { type: 'string' },
              summary: { type: 'string', nullable: true },
              price: { type: 'number', nullable: true },
              bedrooms: { type: 'integer', nullable: true },
              bathrooms: { type: 'integer', nullable: true },
              propertyTypeId: { type: 'integer' },
              propertyStatusId: { type: 'integer' },
              streetAddress: { type: 'string', nullable: true },
              addressLocality: { type: 'string', nullable: true },
              addressRegion: { type: 'string', nullable: true },
              isFeatured: { type: 'boolean' },
              isPublished: { type: 'boolean' },
              agent: { $ref: '#/components/schemas/PersonResponse' },
            },
          },
          ContactMethodResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              code: { type: 'string' },
              name: { type: 'string' },
              description: { type: 'string', nullable: true },
            },
          },
          LeadSourceResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              code: { type: 'string' },
              name: { type: 'string' },
              description: { type: 'string', nullable: true },
              isActive: { type: 'boolean' },
              sortOrder: { type: 'integer' },
            },
          },
          ContactRequestResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              firstName: { type: 'string' },
              lastName: { type: 'string' },
              email: { type: 'string' },
              phone: { type: 'string', nullable: true },
              companyName: { type: 'string', nullable: true },
              jobTitle: { type: 'string', nullable: true },
              requestTypeId: { type: 'integer' },
              subject: { type: 'string', nullable: true },
              message: { type: 'string' },
              contactMethodId: { type: 'integer', nullable: true },
              contactMethod: { $ref: '#/components/schemas/ContactMethodResponse' },
              leadSourceId: { type: 'integer', nullable: true },
              leadSource: { $ref: '#/components/schemas/LeadSourceResponse' },
              requestStatusId: { type: 'integer' },
              requestStatus: { type: 'object', properties: { id: { type: 'integer' }, name: { type: 'string' }, code: { type: 'string' } } },
              marketingConsent: { type: 'boolean' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
              resolvedAt: { type: 'string', format: 'date-time', nullable: true },
            },
          },
          PropertyImageResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              propertyId: { type: 'integer' },
              imageId: { type: 'integer' },
              isBanner: { type: 'boolean' },
              image: { $ref: '#/components/schemas/ImageResponse' },
            },
          },
          PropertyVideoResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              propertyId: { type: 'integer' },
              videoId: { type: 'integer' },
              video: { $ref: '#/components/schemas/VideoResponse' },
            },
          },
          PropertyReviewResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              propertyId: { type: 'integer' },
              personId: { type: 'integer' },
              associateId: { type: 'integer', nullable: true },
              moderationStatusId: { type: 'integer', nullable: true },
              rating: { type: 'integer' },
              title: { type: 'string', nullable: true },
              comment: { type: 'string', nullable: true },
              isVerified: { type: 'boolean' },
              isPublished: { type: 'boolean' },
              helpfulCount: { type: 'integer' },
              createdAt: { type: 'string', format: 'date-time' },
              person: { $ref: '#/components/schemas/PersonResponse' },
              moderationStatus: { $ref: '#/components/schemas/ReviewModerationStatuses' },
            },
          },
          LoginResponse: {
            type: 'object',
            properties: {
              token: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIs...' },
              personId: { type: 'integer', example: 1 },
              email: { type: 'string', format: 'email', example: 'john@example.com' },
            },
          },
          AuthRegisterResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer', example: 1 },
              email: { type: 'string', format: 'email', example: 'john@example.com' },
            },
          },
          TourRequestResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              propertyId: { type: 'integer' },
              clientPersonId: { type: 'integer', nullable: true },
              clientFirstName: { type: 'string' },
              clientLastName: { type: 'string' },
              clientEmail: { type: 'string' },
              clientPhone: { type: 'string', nullable: true },
              primaryAssociateId: { type: 'integer' },
              secondaryAssociateId: { type: 'integer', nullable: true },
              tourTypeId: { type: 'integer' },
              tourStatusId: { type: 'integer' },
              scheduledDate: { type: 'string', format: 'date-time' },
              clientMessage: { type: 'string', nullable: true },
              associateNotes: { type: 'string', nullable: true },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
              property: { $ref: '#/components/schemas/PropertyResponse' },
              clientPerson: { $ref: '#/components/schemas/PersonResponse' },
              primaryAssociate: { $ref: '#/components/schemas/AssociateResponse' },
              secondaryAssociate: { $ref: '#/components/schemas/AssociateResponse' },
            },
          },
          // --- Newsletter Input Schemas ---
          NewsletterIssueInput: {
            type: 'object',
            required: ['title', 'slug'],
            properties: {
              title: { type: 'string', example: 'Q1 2026 Luxury Market Report' },
              slug: { type: 'string', example: 'q1-2026-luxury-market-report' },
              issueNumber: { type: 'integer', nullable: true, example: 1 },
              summary: { type: 'string', nullable: true },
              coverImageId: { type: 'integer', nullable: true },
              publishedAt: { type: 'string', format: 'date-time', nullable: true },
              isPublished: { type: 'boolean', default: false },
              createdById: { type: 'integer', nullable: true },
            },
          },
          NewsletterSubscriptionInput: {
            type: 'object',
            required: ['personId'],
            properties: {
              personId: { type: 'integer', example: 1 },
              isSubscribed: { type: 'boolean', default: true },
              source: { type: 'string', nullable: true, example: 'property-detail' },
              leadSourceId: { type: 'integer', nullable: true, example: 1 },
              categoryIds: { type: 'array', items: { type: 'integer' }, example: [1, 2] },
            },
          },
          NewsletterCategoryInput: {
            type: 'object',
            required: ['name'],
            properties: {
              name: { type: 'string', example: 'Market Reports' },
            },
          },
          // --- Newsletter Response Schemas ---
          NewsletterIssueResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              title: { type: 'string' },
              slug: { type: 'string' },
              issueNumber: { type: 'integer', nullable: true },
              summary: { type: 'string', nullable: true },
              coverImageId: { type: 'integer', nullable: true },
              publishedAt: { type: 'string', format: 'date-time', nullable: true },
              isPublished: { type: 'boolean' },
              createdById: { type: 'integer', nullable: true },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
              coverImage: { $ref: '#/components/schemas/ImageResponse' },
              createdBy: { $ref: '#/components/schemas/PersonResponse' },
              sections: {
                type: 'array',
                items: { $ref: '#/components/schemas/NewsletterSectionResponse' },
              },
              contents: {
                type: 'array',
                items: { $ref: '#/components/schemas/NewsletterContentResponse' },
              },
              campaigns: {
                type: 'array',
                items: { $ref: '#/components/schemas/NewsletterCampaignResponse' },
              },
            },
          },
          NewsletterSectionResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              newsletterIssueId: { type: 'integer' },
              title: { type: 'string' },
              sortOrder: { type: 'integer' },
              content: { type: 'string', nullable: true },
            },
          },
          NewsletterContentResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              newsletterIssueId: { type: 'integer' },
              newsletterContentTypeId: { type: 'integer' },
              referenceId: { type: 'integer' },
              sortOrder: { type: 'integer' },
              newsletterContentType: { $ref: '#/components/schemas/NewsletterContentTypeResponse' },
            },
          },
          NewsletterContentTypeResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              name: { type: 'string' },
              description: { type: 'string', nullable: true },
            },
          },
          NewsletterCampaignResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              newsletterIssueId: { type: 'integer' },
              sentAt: { type: 'string', format: 'date-time', nullable: true },
              recipientsCount: { type: 'integer' },
              openCount: { type: 'integer' },
              clickCount: { type: 'integer' },
              createdAt: { type: 'string', format: 'date-time' },
            },
          },
          NewsletterSubscriptionResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              personId: { type: 'integer' },
              isSubscribed: { type: 'boolean' },
              subscribedAt: { type: 'string', format: 'date-time' },
              unsubscribedAt: { type: 'string', format: 'date-time', nullable: true },
              source: { type: 'string', nullable: true },
              person: { $ref: '#/components/schemas/PersonResponse' },
              categories: {
                type: 'array',
                items: { $ref: '#/components/schemas/NewsletterSubscriptionCategoryResponse' },
              },
            },
          },
          NewsletterCategoryResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              name: { type: 'string' },
            },
          },
          RoleResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              code: { type: 'string' },
              name: { type: 'string' },
              description: { type: 'string', nullable: true },
              isActive: { type: 'boolean' },
              isSystem: { type: 'boolean' },
              sortOrder: { type: 'integer' },
            },
          },
          PermissionResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              code: { type: 'string' },
              name: { type: 'string' },
              description: { type: 'string', nullable: true },
              category: { type: 'string', nullable: true },
              isActive: { type: 'boolean' },
              isSystem: { type: 'boolean' },
              sortOrder: { type: 'integer' },
            },
          },
          NewsletterSubscriptionCategoryResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              newsletterSubscriptionId: { type: 'integer' },
              newsletterCategoryId: { type: 'integer' },
              newsletterCategory: { $ref: '#/components/schemas/NewsletterCategoryResponse' },
            },
          },
          TenantResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              name: { type: 'string' },
              slug: { type: 'string' },
              domain: { type: 'string', nullable: true },
              logoUrl: { type: 'string', nullable: true },
              faviconUrl: { type: 'string', nullable: true },
              primaryColor: { type: 'string', nullable: true },
              isActive: { type: 'boolean' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          TenantSettingsResponse: {
            type: 'object',
            properties: {
              id: { type: 'integer' },
              tenantId: { type: 'integer' },
              companyName: { type: 'string', nullable: true },
              tagline: { type: 'string', nullable: true },
              contactEmail: { type: 'string', nullable: true },
              contactPhone: { type: 'string', nullable: true },
              address: { type: 'string', nullable: true },
              socialFacebook: { type: 'string', nullable: true },
              socialInstagram: { type: 'string', nullable: true },
              socialLinkedin: { type: 'string', nullable: true },
              socialTwitter: { type: 'string', nullable: true },
              googleAnalyticsId: { type: 'string', nullable: true },
              metaTitle: { type: 'string', nullable: true },
              metaDescription: { type: 'string', nullable: true },
            },
          },
        },
      },
    },
  });
  return NextResponse.json(spec);
}
